//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batches_02
    {
        public long pickid { get; set; }
        public string finyear { get; set; }
        public string loomNo { get; set; }
        public int batchNo { get; set; }
        public decimal pick { get; set; }
        public decimal weft { get; set; }
    
        public virtual Batch Batch { get; set; }
    }
}
