//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.Batches_01 = new HashSet<Batches_01>();
            this.Batches_02 = new HashSet<Batches_02>();
            this.PackSlipDetls = new HashSet<PackSlipDetl>();
            this.PackSlipReqdetls = new HashSet<PackSlipReqdetl>();
        }
    
        public string finYear { get; set; }
        public string loomNo { get; set; }
        public int BatchNo { get; set; }
        public System.DateTime BatchCreated { get; set; }
        public Nullable<int> inspectorId { get; set; }
        public Nullable<System.DateTime> inspectedDate { get; set; }
        public Nullable<int> prodCode { get; set; }
        public string QcCode { get; set; }
        public Nullable<int> GwnCode { get; set; }
        public string stacksId { get; set; }
        public Nullable<int> Mtrs { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string width { get; set; }
        public int status { get; set; }
        public Nullable<int> machinId { get; set; }
        public Nullable<int> verifiedId { get; set; }
        public bool Rejected { get; set; }
        public string Rejected_Reason { get; set; }
        public byte transtype { get; set; }
        public string narration { get; set; }
        public int GradeId { get; set; }
        public string setNo { get; set; }
        public Nullable<decimal> kara { get; set; }
        public Nullable<decimal> weft { get; set; }
        public Nullable<decimal> pick { get; set; }
        public Nullable<decimal> sample_mtr { get; set; }
        public Nullable<decimal> cutpiece_mtr { get; set; }
        public string beamNo { get; set; }
        public Nullable<decimal> gray_mtr { get; set; }
        public Nullable<decimal> std_width { get; set; }
        public Nullable<decimal> std_pick { get; set; }
        public Nullable<decimal> std_weight { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> finished_Mtr { get; set; }
        public Nullable<decimal> points { get; set; }
        public string grading { get; set; }
        public Nullable<decimal> dp { get; set; }
        public Nullable<long> sales_orderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batches_01> Batches_01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batches_02> Batches_02 { get; set; }
        public virtual grade grade { get; set; }
        public virtual Inspector Inspector { get; set; }
        public virtual Inspector Inspector1 { get; set; }
        public virtual machin machin { get; set; }
        public virtual Quality Quality { get; set; }
        public virtual SetBeem SetBeem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackSlipDetl> PackSlipDetls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackSlipReqdetl> PackSlipReqdetls { get; set; }
        public virtual Batch Batches1 { get; set; }
        public virtual Batch Batch1 { get; set; }
        public virtual mst014 mst014 { get; set; }
        public virtual sales001 sales001 { get; set; }
    }
}
