//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Broker()
        {
            this.sales001 = new HashSet<sales001>();
        }
    
        public int brokerCode { get; set; }
        public string brokerName { get; set; }
        public string brokerAddress { get; set; }
        public string contactNo { get; set; }
        public string GSTN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales001> sales001 { get; set; }
    }
}
