//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentStock
    {
        public string finyear { get; set; }
        public string loomNo { get; set; }
        public int BatchNo { get; set; }
        public int Mtrs { get; set; }
        public Nullable<System.DateTime> scannedDate { get; set; }
        public string createdbyid { get; set; }
    }
}
