//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarmentBatchEntities : DbContext
    {
        public GarmentBatchEntities()
            : base("name=GarmentBatchEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batches_01> Batches_01 { get; set; }
        public virtual DbSet<Broker> Brokers { get; set; }
        public virtual DbSet<Count> Counts { get; set; }
        public virtual DbSet<CurrentStock> CurrentStocks { get; set; }
        public virtual DbSet<Inspector> Inspectors { get; set; }
        public virtual DbSet<localuser> localusers { get; set; }
        public virtual DbSet<localuser1> localuser1 { get; set; }
        public virtual DbSet<localuser3> localuser3 { get; set; }
        public virtual DbSet<localuser4> localuser4 { get; set; }
        public virtual DbSet<machin> machins { get; set; }
        public virtual DbSet<Mill> Mills { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<moduleuser> moduleusers { get; set; }
        public virtual DbSet<packSlip_002> packSlip_002 { get; set; }
        public virtual DbSet<PackSliphead> PackSlipheads { get; set; }
        public virtual DbSet<Quality> Qualities { get; set; }
        public virtual DbSet<sales001_00> sales001_00 { get; set; }
        public virtual DbSet<sales001_01> sales001_01 { get; set; }
        public virtual DbSet<SetBeem> SetBeems { get; set; }
        public virtual DbSet<SetCreation> SetCreations { get; set; }
        public virtual DbSet<Stack> Stacks { get; set; }
        public virtual DbSet<PackSlipReqdetl> PackSlipReqdetls { get; set; }
        public virtual DbSet<mst011> mst011 { get; set; }
        public virtual DbSet<grade> grades { get; set; }
        public virtual DbSet<mst004> mst004 { get; set; }
        public virtual DbSet<mst011_01> mst011_01 { get; set; }
        public virtual DbSet<localuser2> localuser2 { get; set; }
        public virtual DbSet<Batches_02> Batches_02 { get; set; }
        public virtual DbSet<PackSlipDetl> PackSlipDetls { get; set; }
        public virtual DbSet<mst005> mst005 { get; set; }
        public virtual DbSet<mst005_01> mst005_01 { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<PackSlipReqhead> PackSlipReqheads { get; set; }
        public virtual DbSet<mst014> mst014 { get; set; }
        public virtual DbSet<sales001> sales001 { get; set; }
        public virtual DbSet<mst006> mst006 { get; set; }
    }
}
