//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localuser1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public localuser1()
        {
            this.localuser2 = new HashSet<localuser2>();
        }
    
        public int ID { get; set; }
        public string userlevel_name { get; set; }
        public string comments { get; set; }
    
        public virtual localuser4 localuser4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<localuser2> localuser2 { get; set; }
    }
}
