//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localuser3
    {
        public int ID { get; set; }
        public bool A { get; set; }
        public bool E { get; set; }
        public bool D { get; set; }
        public bool L { get; set; }
        public bool P { get; set; }
        public bool SysAdmin { get; set; }
        public bool O { get; set; }
    
        public virtual localuser2 localuser2 { get; set; }
    }
}
