//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localuser2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public localuser2()
        {
            this.moduleusers = new HashSet<moduleuser>();
        }
    
        public int ID { get; set; }
        public string username { get; set; }
        public string UserLongName { get; set; }
        public int UserLevelID { get; set; }
        public string mobileno { get; set; }
        public string email_id { get; set; }
    
        public virtual localuser localuser { get; set; }
        public virtual localuser1 localuser1 { get; set; }
        public virtual localuser3 localuser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moduleuser> moduleusers { get; set; }
    }
}
