//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mill
    {
        public int millCode { get; set; }
        public string millName { get; set; }
        public string City { get; set; }
        public string GSTIN { get; set; }
        public string address { get; set; }
    }
}
