//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst005_01
    {
        public int firm_id { get; set; }
        public string div_id { get; set; }
        public bool active { get; set; }
        public string cf_div_id { get; set; }
        public bool freez { get; set; }
    
        public virtual mst004 mst004 { get; set; }
        public virtual mst005 mst005 { get; set; }
    }
}
