//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst014
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst014()
        {
            this.Batches = new HashSet<Batch>();
            this.Stacks = new HashSet<Stack>();
        }
    
        public int L_Id { get; set; }
        public string L_Name { get; set; }
        public string L_Alias { get; set; }
        public string L_Address { get; set; }
        public Nullable<int> L_city_id { get; set; }
        public string branch_id { get; set; }
        public Nullable<bool> in_type { get; set; }
        public string CreatedUser { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual mst014 mst0141 { get; set; }
        public virtual mst014 mst0142 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stack> Stacks { get; set; }
        public virtual mst006 mst006 { get; set; }
    }
}
