//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst004
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst004()
        {
            this.mst005_01 = new HashSet<mst005_01>();
        }
    
        public int firm_code { get; set; }
        public string firm_name { get; set; }
        public string firm_alias { get; set; }
        public string firm_address { get; set; }
        public string firm_fno { get; set; }
        public string email_id { get; set; }
        public string web_address { get; set; }
        public Nullable<int> firm_cityId { get; set; }
        public string Jurisdiction { get; set; }
        public string firm_cin { get; set; }
        public string firm_pan { get; set; }
        public bool active { get; set; }
        public string firm_bank_name { get; set; }
        public string firm_bank_accno { get; set; }
        public string firm_bank_ifsc { get; set; }
        public Nullable<int> natofbus { get; set; }
        public string CreatedUser { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public bool is_membership { get; set; }
        public string firm_swift_code { get; set; }
        public string firm_Bankbranch { get; set; }
        public string eic_no { get; set; }
        public string firm_bank_holder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst005_01> mst005_01 { get; set; }
        public virtual mst006 mst006 { get; set; }
    }
}
