//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst011_01
    {
        public int acc_code { get; set; }
        public string acc_address { get; set; }
        public Nullable<int> city_code { get; set; }
        public string contact_person { get; set; }
        public string contact_designation { get; set; }
        public string contact_mobile_no { get; set; }
        public string off_tel_no { get; set; }
        public string email_id { get; set; }
        public string year_of_establishment { get; set; }
        public string website { get; set; }
        public string pan_no { get; set; }
        public string cin_no { get; set; }
    
        public virtual mst011 mst011 { get; set; }
        public virtual mst006 mst006 { get; set; }
    }
}
