//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackSlipReqdetl
    {
        public long detl_id { get; set; }
        public int req_id { get; set; }
        public string finyear { get; set; }
        public string loomNo { get; set; }
        public int BatchNo { get; set; }
        public int mtr { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual PackSlipReqhead PackSlipReqhead { get; set; }
    }
}
