//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackSlipDetl
    {
        public long slipdetlId { get; set; }
        public int SlipId { get; set; }
        public string finyear { get; set; }
        public string loomNo { get; set; }
        public int BatchNo { get; set; }
        public int mtr { get; set; }
        public decimal weight { get; set; }
        public string description { get; set; }
        public bool scanned { get; set; }
    
        public virtual PackSliphead PackSliphead { get; set; }
        public virtual Batch Batch { get; set; }
    }
}
