//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class packSlip_002
    {
        public int SlipId { get; set; }
        public string vehical_img { get; set; }
        public string terms { get; set; }
    
        public virtual PackSliphead PackSliphead { get; set; }
    }
}
