//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackSliphead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackSliphead()
        {
            this.PackSlipDetls = new HashSet<PackSlipDetl>();
        }
    
        public int SlipId { get; set; }
        public string finyear { get; set; }
        public int SlipNo { get; set; }
        public int custId { get; set; }
        public System.DateTime SlipDate { get; set; }
        public int prodCode { get; set; }
        public string QcCode { get; set; }
        public string Nar { get; set; }
        public string vehicleNo { get; set; }
        public Nullable<int> totalMtrs { get; set; }
        public Nullable<decimal> totalWeight { get; set; }
        public Nullable<int> req_id { get; set; }
        public string CreatedUser { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public int dctype { get; set; }
        public Nullable<long> style_id { get; set; }
        public string invoiceNo { get; set; }
    
        public virtual packSlip_002 packSlip_002 { get; set; }
        public virtual Quality Quality { get; set; }
        public virtual mst011 mst011 { get; set; }
        public virtual PackSliphead PackSliphead1 { get; set; }
        public virtual PackSliphead PackSliphead2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackSlipDetl> PackSlipDetls { get; set; }
        public virtual product product { get; set; }
        public virtual PackSlipReqhead PackSlipReqhead { get; set; }
    }
}
