//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackSlipReqhead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackSlipReqhead()
        {
            this.PackSlipheads = new HashSet<PackSliphead>();
            this.PackSlipReqdetls = new HashSet<PackSlipReqdetl>();
        }
    
        public int req_id { get; set; }
        public string finyear { get; set; }
        public int req_no { get; set; }
        public System.DateTime req_date { get; set; }
        public int prodCode { get; set; }
        public string QcCode { get; set; }
        public int totalMtrs { get; set; }
        public bool accept { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> so_detl { get; set; }
        public Nullable<int> cust_id { get; set; }
        public string naration { get; set; }
        public byte grade_id { get; set; }
        public byte status_id { get; set; }
        public Nullable<int> scannedMtrs { get; set; }
        public Nullable<bool> isOrderComplete { get; set; }
    
        public virtual mst011 mst011 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackSliphead> PackSlipheads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackSlipReqdetl> PackSlipReqdetls { get; set; }
        public virtual product product { get; set; }
        public virtual sales001_01 sales001_01 { get; set; }
        public virtual Quality Quality { get; set; }
    }
}
