//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.PackSlipheads = new HashSet<PackSliphead>();
            this.Qualities = new HashSet<Quality>();
            this.PackSlipReqheads = new HashSet<PackSlipReqhead>();
        }
    
        public int prodCode { get; set; }
        public string prodName { get; set; }
        public Nullable<decimal> gms_limit { get; set; }
        public Nullable<decimal> gpm_min { get; set; }
        public Nullable<decimal> gpm { get; set; }
        public Nullable<int> costId { get; set; }
        public decimal shrinkage { get; set; }
        public string composition { get; set; }
        public string color { get; set; }
        public string weightOz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackSliphead> PackSlipheads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quality> Qualities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackSlipReqhead> PackSlipReqheads { get; set; }
    }
}
