//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales001_01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales001_01()
        {
            this.PackSlipReqheads = new HashSet<PackSlipReqhead>();
        }
    
        public long detl_id { get; set; }
        public long vch_id { get; set; }
        public string qc_code { get; set; }
        public int prod_code { get; set; }
        public int roll { get; set; }
        public int mtrs { get; set; }
        public decimal amount { get; set; }
        public string naration { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<byte> grade_id { get; set; }
    
        public virtual Quality Quality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackSlipReqhead> PackSlipReqheads { get; set; }
        public virtual sales001 sales001 { get; set; }
    }
}
