//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales001_00
    {
        public long vch_id { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
    
        public virtual sales001 sales001 { get; set; }
    }
}
