//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales001
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales001()
        {
            this.Batches = new HashSet<Batch>();
            this.sales001_01 = new HashSet<sales001_01>();
        }
    
        public long vch_id { get; set; }
        public string fin_year { get; set; }
        public int vch_no { get; set; }
        public System.DateTime vch_date { get; set; }
        public string order_no { get; set; }
        public string ref_no { get; set; }
        public Nullable<System.DateTime> ref_date { get; set; }
        public int cust_id { get; set; }
        public string cust_gstin { get; set; }
        public Nullable<int> broker_code { get; set; }
        public string broker_gstin { get; set; }
        public string delivery_schedule { get; set; }
        public decimal total_amt { get; set; }
        public string naration { get; set; }
        public int delivery_period { get; set; }
        public string ICE_gstTaxpayer { get; set; }
        public string IF_goodsImportar { get; set; }
        public string RC_costomRegister { get; set; }
        public string portName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual Broker Broker { get; set; }
        public virtual mst011 mst011 { get; set; }
        public virtual sales001_00 sales001_00 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales001_01> sales001_01 { get; set; }
    }
}
