//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetBeem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetBeem()
        {
            this.Batches = new HashSet<Batch>();
        }
    
        public string setNo { get; set; }
        public string beemNo { get; set; }
        public decimal deyingLength { get; set; }
        public Nullable<long> opvchid { get; set; }
        public Nullable<long> invchid { get; set; }
        public string finyear { get; set; }
        public System.DateTime sb_created_date { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<long> detl_id { get; set; }
    
        public virtual SetCreation SetCreation { get; set; }
        public virtual SetBeem SetBeem1 { get; set; }
        public virtual SetBeem SetBeem2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
    }
}
